const express = require("express");
const nodemailer = require("nodemailer");
const router = express.Router();
const { emailRegex } = require("../config");
const locale = require("../locales/en.json");
require("dotenv").config();

const emailTexts = {
    tr: {
        admin: {
            subject: "🐛 [Monera] Yeni Sorun Bildirimi: ",
            newIssue: "🛠️ Yeni Sorun Bildirimi",
            appName: "Monera Uygulaması",
            issueDetails: "📋 Sorun Detayları",
            description: "📝 Açıklama:",
            userInfo: "👤 Kullanıcı Bilgileri",
            email: "📧 E-posta:",
            platform: "💻 Platform:",
            version: "🔢 Versiyon:",
            date: "📅 Tarih:",
            notSpecified: "Belirtilmemiş",
            urgentNote: "⚡ Bu sorun bildirimi acil olarak değerlendirilmeli ve kullanıcıya geri dönüş yapılmalıdır.",
            autoGenerated: "Bu e-posta Monera uygulamasından otomatik olarak gönderilmiştir.",
            copyright: "© 2025 Monera - Tüm hakları saklıdır."
        },
        user: {
            subject: "✅ Sorun Raporunuz Başarıyla Alındı - Monera",
            reportReceived: "✅ Rapor Alındı!",
            thankYou: "Teşekkür ederiz",
            hello: "Merhaba!",
            successMessage: "Monera uygulamasına gönderdiğiniz sorun raporu başarıyla alınmıştır.",
            reportTitle: "📋 Rapor Başlığınız",
            reportDescription: "📋 Rapor Açıklamanız",
            nextSteps: "⏱️ Sonraki Adımlar:",
            step1: "Teknik ekibimiz sorunuzun detaylarını inceleyecek.",
            step2: "Gerekirse size ek bilgi almak için dönüş yapılacak.",
            step3: "Çözüm bulunduğunda bilgilendirileceksiniz.",
            step4: "Genellikle 24 saat içinde geri dönüş yapıyoruz.",
            tip: "💡 İpucu",
            tipText: "Bu e-postayı saklayın! Sorunuzla ilgili güncellemeler için bu e-posta adresini kullanabilirsiniz.",
            thanks: "Teşekkürler! 🙏",
            team: "Monera Geliştirici Ekibi",
            autoGenerated: "Bu e-posta Monera uygulamasından otomatik olarak gönderilmiştir.",
            contact: "Sorularınız için: support@vu4ll.com.tr",
            copyright: "© 2025 Monera - Tüm hakları saklıdır."
        }
    },
    en: {
        admin: {
            subject: "🐛 [Monera] New Issue Report: ",
            newIssue: "🛠️ New Issue Report",
            appName: "Monera Application",
            issueDetails: "📋 Issue Details",
            description: "📝 Description:",
            userInfo: "👤 User Information",
            email: "📧 Email:",
            platform: "💻 Platform:",
            version: "🔢 Version:",
            date: "📅 Date:",
            notSpecified: "Not specified",
            urgentNote: "⚡ This issue report should be evaluated urgently and a response should be made to the user.",
            autoGenerated: "This email was automatically sent from the Monera application.",
            copyright: "© 2025 Monera - All rights reserved."
        },
        user: {
            subject: "✅ Your Issue Report Successfully Received - Monera",
            reportReceived: "✅ Report Received!",
            thankYou: "Thank you",
            hello: "Hello!",
            successMessage: "Your issue report sent to the Monera application has been successfully received.",
            reportTitle: "📋 Your Report Title",
            reportDescription: "📋 Your Report Description",
            nextSteps: "⏱️ Next Steps:",
            step1: "Our technical team will review the details of your issue.",
            step2: "If necessary, we will contact you for additional information.",
            step3: "You will be notified when a solution is found.",
            step4: "We usually respond within 24 hours.",
            tip: "💡 Tip",
            tipText: "Save this email! You can use this email address for updates regarding your issue.",
            thanks: "Thank you! 🙏",
            team: "Monera Development Team",
            autoGenerated: "This email was automatically sent from the Monera application.",
            contact: "For questions: support@vu4ll.com.tr",
            copyright: "© 2025 Monera - All rights reserved."
        }
    }
};

const transporter = nodemailer.createTransport({
    host: process.env.MAIL_HOST,
    port: 587,
    secure: false,
    auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS
    }
});

router.post("/issue", async (req, res) => {
    try {
        const { title, description, email, platform, version, timestamp, language } = req.body;

        if (!title || !description || !email) {
            return res.status(400).json({
                status: res.statusCode,
                success: false,
                message: locale.support.issue.fail.missingFields
            });
        }

        if (!emailRegex.test(email)) {
            return res.status(400).json({
                status: res.statusCode,
                success: false,
                message: locale.support.issue.fail.invalidEmail
            });
        }

        // Determine language (default to Turkish if not specified or invalid)
        const selectedLanguage = (language === 'en' || language === 'tr') ? language : 'tr';
        const texts = emailTexts[selectedLanguage];

        const emailContent = {
            from: `Support - Gider Takip <${process.env.MAIL_USER}>`,
            to: "contact@vu4ll.com.tr",
            subject: `${texts.admin.subject}${title}`,
            html: `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${texts.admin.newIssue}</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">${texts.admin.newIssue}</h1>
        <p style="color: #e8f0fe; margin: 10px 0 0 0; font-size: 14px;">${texts.admin.appName}</p>
    </div>
    
    <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="background: #f8f9fa; border-left: 4px solid #007bff; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h2 style="margin: 0 0 10px 0; color: #007bff; font-size: 18px;">${texts.admin.issueDetails}</h2>
            <p style="margin: 0; font-weight: bold; font-size: 16px;">${title}</p>
        </div>
        
        <div style="margin-bottom: 25px;">
            <h3 style="color: #495057; margin: 0 0 10px 0; font-size: 16px;">${texts.admin.description}</h3>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
                ${description.replace(/\n/g, "<br>")}
            </div>
        </div>
        
        <div style="background: #e3f2fd; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h3 style="color: #1976d2; margin: 0 0 15px 0; font-size: 16px;">${texts.admin.userInfo}</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 0; font-weight: bold; width: 30%;">${texts.admin.email}</td>
                    <td style="padding: 8px 0;">${email}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${texts.admin.platform}</td>
                    <td style="padding: 8px 0;">${platform || texts.admin.notSpecified}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${texts.admin.version}</td>
                    <td style="padding: 8px 0;">${version || texts.admin.notSpecified}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${texts.admin.date}</td>
                    <td style="padding: 8px 0;">${new Date(timestamp).toLocaleString(selectedLanguage === 'tr' ? 'tr-TR' : 'en-US')}</td>
                </tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 20px; background: #fff3cd; border-radius: 8px; border: 1px solid #ffeaa7;">
            <p style="margin: 0; color: #856404; font-size: 14px;">
                ${texts.admin.urgentNote}
            </p>
        </div>
    </div>
    
    <div style="text-align: center; padding: 20px; color: #6c757d; font-size: 12px;">
        <p style="margin: 0;">${texts.admin.autoGenerated}</p>
        <p style="margin: 5px 0 0 0;">${texts.admin.copyright}</p>
    </div>
</body>
</html>
      `
        };

        await transporter.sendMail(emailContent);

        const confirmationEmail = {
            from: `Support - Gider Takip <${process.env.MAIL_USER}>`,
            to: email,
            subject: texts.user.subject,
            html: `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${texts.user.reportReceived}</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">${texts.user.reportReceived}</h1>
        <p style="color: #e8f5e9; margin: 10px 0 0 0; font-size: 14px;">${texts.user.thankYou}</p>
    </div>
    
    <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="text-align: center; margin-bottom: 25px;">
            <div style="display: inline-block; background: #d4edda; padding: 15px 25px; border-radius: 50px; border: 2px solid #c3e6cb;">
                <span style="font-size: 24px;">🎉</span>
            </div>
        </div>
        
        <h2 style="color: #155724; text-align: center; margin: 0 0 20px 0;">${texts.user.hello}</h2>
        <p style="font-size: 16px; margin-bottom: 20px; text-align: center;">
            ${texts.user.successMessage}
        </p>
        
        <div style="background: #f8f9fa; border-left: 4px solid #28a745; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h3 style="margin: 0 0 10px 0; color: #28a745; font-size: 16px;">${texts.user.reportTitle}</h3>
            <p style="margin: 0; font-weight: bold; font-size: 16px; color: #495057;">${title}</p>
        </div>
        <div style="background: #f8f9fa; border-left: 4px solid #28a745; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h3 style="margin: 0 0 10px 0; color: #28a745; font-size: 16px;">${texts.user.reportDescription}</h3>
            <p style="margin: 0; font-weight: bold; font-size: 16px; color: #495057;">${description.replace(/\n/g, "<br>")}</p>
        </div>
        
        <div style="background: #e3f2fd; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h3 style="color: #1976d2; margin: 0 0 15px 0; font-size: 16px;">${texts.user.nextSteps}</h3>
            <ul style="margin: 0; padding-left: 20px; color: #495057;">
                <li style="margin-bottom: 8px;">${texts.user.step1}</li>
                <li style="margin-bottom: 8px;">${texts.user.step2}</li>
                <li style="margin-bottom: 8px;">${texts.user.step3}</li>
                <li>${texts.user.step4}</li>
            </ul>
        </div>
        
        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; border: 1px solid #ffeaa7; margin-bottom: 25px;">
            <h3 style="color: #856404; margin: 0 0 10px 0; font-size: 16px;">${texts.user.tip}</h3>
            <p style="margin: 0; color: #856404; font-size: 14px;">
                ${texts.user.tipText}
            </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px;">
            <p style="font-size: 18px; color: #28a745; font-weight: bold; margin: 0;">${texts.user.thanks}</p>
            <p style="margin: 10px 0 0 0; color: #6c757d;">${texts.user.team}</p>
        </div>
    </div>
    
    <div style="text-align: center; padding: 20px; color: #6c757d; font-size: 12px;">
        <p style="margin: 0;">${texts.user.autoGenerated}</p>
        <p style="margin: 5px 0 0 0;">${texts.user.contact}</p>
        <p style="margin: 5px 0 0 0;">${texts.user.copyright}</p>
    </div>
</body>
</html>
      `
        };

        await transporter.sendMail(confirmationEmail);

        res.status(200).json({
            status: res.statusCode,
            success: true,
            message: locale.support.issue.success.message
        });

    } catch (error) {
        console.error("Issue submission error:", error);
        res.status(500).json({
            status: res.statusCode,
            success: false,
            message: locale.support.issue.fail.sendError
        });
    }
});

module.exports = router;