const nodemailer = require("nodemailer");
require("dotenv").config();

const transporter = nodemailer.createTransport({
    host: process.env.MAIL_HOST,
    port: 587,
    secure: false,
    auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS
    }
});

const issueMail = async (t, title, description, email, platform, version, timestamp, locale) => {
    const emailContent = {
        from: `Support - Monedsa <${process.env.MAIL_USER}>`,
        to: "contact@vu4ll.com.tr",
        subject: `${t("issueMail.admin.subject")}${title}`,
        html: `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${t("issueMail.admin.newIssue")}</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">${t("issueMail.admin.newIssue")}</h1>
        <p style="color: #e8f0fe; margin: 10px 0 0 0; font-size: 14px;">${t("issueMail.admin.appName")}</p>
    </div>
    
    <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="background: #f8f9fa; border-left: 4px solid #007bff; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h2 style="margin: 0 0 10px 0; color: #007bff; font-size: 18px;">${t("issueMail.admin.issueDetails")}</h2>
            <p style="margin: 0; font-weight: bold; font-size: 16px;">${title}</p>
        </div>
        
        <div style="margin-bottom: 25px;">
            <h3 style="color: #495057; margin: 0 0 10px 0; font-size: 16px;">${t("issueMail.admin.description")}</h3>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
                ${description.replace(/\n/g, "<br>")}
            </div>
        </div>
        
        <div style="background: #e3f2fd; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h3 style="color: #1976d2; margin: 0 0 15px 0; font-size: 16px;">${t("issueMail.admin.userInfo")}</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 0; font-weight: bold; width: 30%;">${t("issueMail.admin.email")}</td>
                    <td style="padding: 8px 0;">${email}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${t("issueMail.admin.platform")}</td>
                    <td style="padding: 8px 0;">${platform || t("issueMail.admin.notSpecified")}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${t("issueMail.admin.version")}</td>
                    <td style="padding: 8px 0;">${version || t("issueMail.admin.notSpecified")}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; font-weight: bold;">${t("issueMail.admin.date")}</td>
                    <td style="padding: 8px 0;">${new Date(timestamp).toLocaleString(locale)}</td>
                </tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 20px; background: #fff3cd; border-radius: 8px; border: 1px solid #ffeaa7;">
            <p style="margin: 0; color: #856404; font-size: 14px;">
                ${t("issueMail.admin.urgentNote")}
            </p>
        </div>
    </div>
    
    <div style="text-align: center; padding: 20px; color: #6c757d; font-size: 12px;">
        <p style="margin: 0;">${t("issueMail.admin.autoGenerated")}</p>
        <p style="margin: 5px 0 0 0;">${t("issueMail.admin.copyright", { year: new Date().getFullYear() })}</p>
    </div>
</body>
</html>
      `
    };

    await transporter.sendMail(emailContent);
};

const userIssueMail = async (t, title, description, email) => {
    const emailContent = {
        from: `Support - Monedsa <${process.env.MAIL_USER}>`,
        to: email,
        subject: t("issueMail.user.subject"),
        html: `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${t("issueMail.user.reportReceived")}</title>
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">${t("issueMail.user.reportReceived")}</h1>
        <p style="color: #e8f5e9; margin: 10px 0 0 0; font-size: 14px;">${t("issueMail.user.thankYou")}</p>
    </div>
    
    <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="text-align: center; margin-bottom: 25px;">
            <div style="display: inline-block; background: #d4edda; padding: 15px 25px; border-radius: 50px; border: 2px solid #c3e6cb;">
                <span style="font-size: 24px;">🎉</span>
            </div>
        </div>
        
        <h2 style="color: #155724; text-align: center; margin: 0 0 20px 0;">${t("issueMail.user.hello")}</h2>
        <p style="font-size: 16px; margin-bottom: 20px; text-align: center;">
            ${t("issueMail.user.successMessage")}
        </p>
        
        <div style="background: #f8f9fa; border-left: 4px solid #28a745; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h3 style="margin: 0 0 10px 0; color: #28a745; font-size: 16px;">${t("issueMail.user.reportTitle")}</h3>
            <p style="margin: 0; font-weight: bold; font-size: 16px; color: #495057;">${title}</p>
        </div>
        <div style="background: #f8f9fa; border-left: 4px solid #28a745; padding: 20px; margin-bottom: 25px; border-radius: 0 5px 5px 0;">
            <h3 style="margin: 0 0 10px 0; color: #28a745; font-size: 16px;">${t("issueMail.user.reportDescription")}</h3>
            <p style="margin: 0; font-weight: bold; font-size: 16px; color: #495057;">${description.replace(/\n/g, "<br>")}</p>
        </div>
        
        <div style="background: #e3f2fd; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h3 style="color: #1976d2; margin: 0 0 15px 0; font-size: 16px;">${t("issueMail.user.nextSteps")}</h3>
            <ul style="margin: 0; padding-left: 20px; color: #495057;">
                <li style="margin-bottom: 8px;">${t("issueMail.user.step1")}</li>
                <li style="margin-bottom: 8px;">${t("issueMail.user.step2")}</li>
                <li style="margin-bottom: 8px;">${t("issueMail.user.step3")}</li>
                <li>${t("issueMail.user.step4")}</li>
            </ul>
        </div>
        
        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; border: 1px solid #ffeaa7; margin-bottom: 25px;">
            <h3 style="color: #856404; margin: 0 0 10px 0; font-size: 16px;">${t("issueMail.user.tip")}</h3>
            <p style="margin: 0; color: #856404; font-size: 14px;">
                ${t("issueMail.user.tipText")}
            </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px;">
            <p style="font-size: 18px; color: #28a745; font-weight: bold; margin: 0;">${t("issueMail.user.thanks")}</p>
            <p style="margin: 10px 0 0 0; color: #6c757d;">${t("issueMail.user.team")}</p>
        </div>
    </div>
    
    <div style="text-align: center; padding: 20px; color: #6c757d; font-size: 12px;">
        <p style="margin: 0;">${t("issueMail.user.autoGenerated")}</p>
        <p style="margin: 5px 0 0 0;">${t("issueMail.user.contact")} <a href="mailto:support@vu4ll.com.tr">support@vu4ll.com.tr</a></p>
        <p style="margin: 5px 0 0 0;">${t("issueMail.user.copyright", { year: new Date().getFullYear() })}</p>
    </div>
</body>
</html>
      `
    };

    await transporter.sendMail(emailContent);
};

module.exports = { userIssueMail, issueMail };